### PR TITLE
Add support for special color for non-inferable calls

### PR DESCRIPTION
**Pull request by tkluck**
As ~~stolen from~~ inspired by [ProfileView](https://github.com/timholy/ProfileView.jl), and suggested by @tpapp in #9.

This commit represents a first ugly attempt for getting feedback. @tpapp, @NHDaly how does something like this look to you?

### CODE REVIEW

**Comment by tpapp** [comment]
Thanks for doing this. I will test today or tomorrow.

**Comment by NHDaly** [comment]
I guess my big question is do we know for sure that the order of the items in `data` will be sane, such that `invoke` will be immediately followed by the function it `invoke`s?

Also, sorry for my ignorance, how do calls to `invoke` relate to type-instability?

**Comment by tpapp** [comment]
Sorry that I did not get back on this, I tested it now with
```julia
using StatProfilerHTML, Profile
f(n) = [g() for _ in 1:n]
@noinline g() = rand() < 0.5 ? 1 : 1.0
f(100)
Profile.clear()
@profile f(10000)
statprofilehtml()
```
but not sure which color is supposed to indicate type instability.

**Comment by tkluck** [comment]
Closing this as I'm hoping to use ProfileSVG in the not-too-distant future.

**Pull request closed without merging**
